build: false

skip_commits:
  files:
    - .travis.yml
    
environment:
    PYTHON_HOME: "C:\\Python37"

    CONAN_STABLE_BRANCH_PATTERN: "stable/*"
    CONAN_UPLOAD: http://cytosplore.lumc.nl:8081/artifactory/api/conan/conan-local
    CONAN_USERNAME: "lkeb" # name used for package naming
    CONAN_CHANNEL: "stable" # channel used for package naming 
    CONAN_LOGIN_USERNAME: "admin"
    CONAN_PASSWORD:
        secure: g+1lNdgrCLmyKNf3KvbHSln5A1H7BsVhsMsIbwgo+UU=    
    CONAN_UPLOAD_ONLY_WHEN_STABLE: 1
    
    matrix:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
            # see https://github.com/conan-io/conan-package-tools for all environment options
          CONAN_VISUAL_VERSIONS: 15
          CONAN_VISUAL_RUNTIMES: MD
          CONAN_ARCHS: x86_64
          CONAN_BUILD_TYPES: Release

install:
  - set PATH=%PYTHON_HOME%;%PYTHON_HOME%/Scripts/;%PATH%
  - pip.exe install conan --upgrade
  - pip.exe install conan_package_tools bincrafters_package_tools
  - conan user # It creates the conan data directory

notifications:
  - provider: Email
    to: 
        - b.van_lew@lumc.nl
    subject: Test hdps-core {{status}}
    message: "URL is {{buildUrl}} Commit ID {{commitId}}."
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true  
  
build_script:
  - python build.py
