name: "Common build install steps"
description: "Install conan and other required python libs"
author: "Baldur van Lew"

inputs:
  conan_version:
    description: "Exact conan version to be installed for example 1.40.4 (optional - installs latest)"
    required: false
    default: "latest"

outputs:
  version:
    description: "The actual conan verion installed"
    value: ${{ steps.get_version.outputs.version }}

runs:
  using: "composite"
  steps:
    - run: |
        python -m pip install --upgrade pip
        pip install wheel setuptools
        if [[ ${{ inputs.conan_version }} == "latest" ]]; then
          pip install conan --upgrade
        else
          pip install conan==${{ inputs.conan_version }}
        fi
      shell: bash

    - name: Fix path on Linux
      run: |
        echo "/home/runner/.local/bin" >> $GITHUB_PATH
      shell: bash

    - name: Create conan user
      run: |
        conan user
      shell: bash

    - name: Fill in output variable
      id: get_version
      shell: bash
      run: |
        conan --version
        echo "::set-output name=version::$(conan --version)"
